    openapi: 3.0.1
    info:
      title: Scalr task todo api
      description: 'This small api is used to manage todo tasks'
      contact:
        email: a.penchuk@scalr.com
      version: 1.0.0
    servers:
    - url: http://localhost:5000
    paths:
      /tasks:
        get:
          summary: Get all tasks from database
          operationId: get_tasks
          responses:
            200:
              description: successful operation
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/TaskListingDocument'
        post:
          summary: Create new task object
          operationId: create_task
          requestBody:
            description: Todo object that needs to be created
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/TaskDocument'
            required: true
          responses:
            201:
              description: The created task
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/TaskDocument'
      /tasks/{id}:
        parameters:
        - name: taskId
          in: path
          description: The id of the task to retrieve
          required: true
          schema:
            type: string
        get:
          summary: Retrieve task by id
          operationId: get_task
          responses:
            200:
              description: The retrieved task
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/TaskDocument'
            404:
              description: Task not found
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      error:
                        type: string
        patch:
          summary: Update task by id
          operationId: update_task
          responses:
            200:
              description: The updated task
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/TaskDocument'
            400:
              description: Bad request
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      error:
                        type: string
            404:
              description: Task not found
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      error:
                        type: string
        delete:
          summary: Delete task
          operationId: delete_task
          responses:
            204:
              description: Task deleted
            400:
              description: Bad request
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      error:
                        type: string
            404:
              description: Task not found
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      error:
                        type: string
      /tasks/{id}/logs:
       parameters:
       - name: taskId
         in: path
         description: The ID of the task
         required: true
         schema:
           type: string
       get:
        summary: Retrieve task logs
        operationId: get_task_logs
        responses:
            200:
              description: The task logs
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      data:
                        type: string
            404:
              description: Task not found or no logs available
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      error:
                        type: string
    components:
     schemas:
      TaskResultDocument:
          description: |-
            JSON:API Document.

            see: https://jsonapi.org/format/#document-structure
          properties:
            data:
              $ref: '#/components/schemas/TaskResult'
            included:
              items:
                type: object
              readOnly: true
              type: array
            meta:
              readOnly: true
              type: object
          type: object
      TaskDocument:
          description: |-
            JSON:API Document.

            see: https://jsonapi.org/format/#document-structure
          properties:
            data:
              $ref: '#/components/schemas/Task'
            included:
              items:
                type: object
              readOnly: true
              type: array
            meta:
              readOnly: true
              type: object
          type: object
      TaskListingDocument:
          description: |-
            JSON:API Document Listing
            see: https://jsonapi.org/format/#document-structure
          properties:
            data:
              items:
                $ref: '#/components/schemas/Task'
              type: array
            included:
              items:
                type: object
              readOnly: true
              type: array
            links:
              additionalProperties:
                type: string
              readOnly: true
              type: object
            meta:
              readOnly: true
              type: object
          type: object
      Task:
          description: The Docker task object model
          properties:
            id:
              readOnly: true
              type: string
            type:
              enum:
              - tasks
              type: string
            attributes:
              properties:
                title:
                  description: The name of the task.
                  readOnly: true
                  type: string
                  example: 'Task 1'
                description:
                  description: The description of the task.
                  type: string
                  example: 'Hello world on ubuntu'
                command:
                  description: The command to run.
                  readOnly: true
                  type: string
                  example: echo Hello World
                image:
                  description: The image to run.
                  readOnly: true
                  type: string
                  example: ubuntu
                status:
                  description: "The task status"
                  readOnly: true
                  enum:
                    - pending
                    - running
                    - finished
                    - failed
                execution-time:
                  type: integer
                  description: "The task execution time"
                  readOnly: true
              required:
                - title
                - image
                - command
            links:
              properties:
                self:
                    description: "The self url link"
                    type: string
                    format: url
                logs:
                    description: "The self url link"
                    type: string
                    format: url
              type: object
              readOnly: true
          required:
          - type
          type: object